spring:
  application:
    name: ai-project-generator-screenshot
  profiles:
    active: local
server:
  port: 8127
  servlet:
    context-path: /api
# Dubbo
dubbo:
  registry:
    address: nacos://127.0.0.1:8848?username=nacos&password=nacos
    register-mode: instance
  protocol:
    name: tri
    port: 50052
  consumer:
    timeout: 120000
  provider:
    timeout: 120000

